### ISSUE TITLE
Scroll Sync not working between any browser

### ISSUE THREAD

**Issue by jljorgenson18** [BrowserSync/grunt-browser-sync#100]
Hello,
First off, Browser Sync is awesome.

I just did a fresh install and everything seems to be working fine on my end except scroll. Here is my current config and other related configs.

Browser Sync
```js
browserSync: {
            dev: {
                bsFiles: {
                    src: [
                        'resources/css/dev/main.css',
                        'devBuilds/index.html',
                        'devBuilds/app.built.js'
                    ]
                },
                options: {
                    watchTask: true,
                    proxy: "localhost:9001",
                    open: false,
                    ghostMode: {
                        clicks: true,
                        forms: true,
                        scroll: true
                    }
                }
            }
        }
```
Watch Configs

```js
module.exports = {
    appCommon: {
        files: ['app/common/**/*.js'],
        options: {
            livereload: true
        },
        tasks: ['jsbeautifier:appCommon', 'jshint:appCommon']
    },
    appServer: {
        files: ['server.js', 'app/server/**/*.js'],
        tasks: ['jsbeautifier:appServer', 'jshint:appServer']
    },
    appUI: {
        files: ['app/ui/**/*.js'],
        options: {
            livereload: true
        },
        tasks: ['jsbeautifier:appUI', 'jshint:appUI', 'browserify:dev']
    },
    appReact: {
        files: ['app/ui/components/**/*.jsx'],
        tasks: ['react']
    },
    sass: {
        files: ['resources/**/*.scss'],
        // options: {
        //     livereload: true
        // },
        tasks: ['compass:dev', 'autoprefixer:dev']
    },
    testing: {
        files: ['quality/testing/**/*.js'],
        options: {
            livereload: true
        },
        tasks: ['jsbeautifier:testing', 'jshint:testing']
    },
    grunt: {
        files: ['Gruntfile.js', 'gruntConfigs/**/*.js'],
        tasks: ['jsbeautifier:grunt', 'jshint:grunt']
    }
};
```

And the default grunt task that I'm running

`grunt.registerTask('default', ['connect:devServer', 'browserSync', 'watch']);`

The proxy server that is referenced is simply a grunt connect server with some custom middleware. I've tried various options include turning off live-reload in many different areas, trying different variations with the ghostmode config, and running "watch" and browserSync" in two different tasks. Nothing seems to be working.

Thanks!

**Comment by shakyShane** [comment]
So, does the browser reload when you can files? And do you see "Connected to BrowserSync" when the browser opens?

**Comment by jljorgenson18** [comment]
The browser is connecting to browser sync and all other features are working except scrolling. The browser is reloading when I change files due to live reload options on various watch tasks.

**Comment by shakyShane** [comment]
Is the main body scrolling, or is it a separate container inside with `overflow: scroll` ?

**Comment by jljorgenson18** [comment]
Sorry for the very late response. The main body is scrolling

**Comment by VinnyFonseca** [comment]
Having the same issue here, any ideas?

**Comment by jljorgenson18** [comment]
So I'm using React Router and I just read that the router manages scroll position (https://github.com/rackt/react-router/blob/master/docs/guides/overview.md#scrolling). This might explain it.

**Comment by VinnyFonseca** [comment]
I have an amp stack so I turned the server off. The UI sends the reload command to all devices properly, but only a single device (a blackberry, of all things) syncs scroll, injection and url changes correctly. All other devices (ipad 3, iphone 4, nexus 7 and nexus 4) accept css injection, form input sync and page reload, but not url changing or scroll.

Here is my grunt file:

	'use strict';

	module.exports = function(grunt) {
		grunt.initConfig({
			pkg: grunt.file.readJSON('package.json'),

			// CONFIG ===================================/

			// Config for grunt-autoprefixer (avoid unnecessary mixin usage)

			autoprefixer: {
				dist: {
					options: {
						safe: true,
						map: true,
						browsers: ['last 3 versions', '> 1%', 'ie 8', 'ie 7']
					},
					files: [{
						expand: true,
						cwd: 'styles',
						src: '{,*/}*.css',
						dest: 'styles',
						ext: '.css'
					}]
				}
			},


			// Config for grunt-contrib-sass (no compass, ~6s compiling time)

			sass: {
				dist: {
					options: {
						style: 'compressed'
					},
					files: [{
						expand: true,
						cwd: 'styles',
						src: '{,*/}*.{scss,sass}',
						dest: 'styles',
						ext: '.css'
					}]
				}
			},


			// Config for grunt-contrib-uglify (javascript concatenation)

			uglify: {
				dist: {
					options: {
						beautify: false,
						sourceMap: true,
						sourceMapIncludeSources: true,
						sourceMapName: 'scripts/build.js.map'
					},
					files: {
						'scripts/build.js': [
							'scripts/core/vendor/jquery-1.11.2.js',
							'scripts/core/vendor/modernizr-latest.js',
							'scripts/core/vendor/device.js',
							'scripts/dev/config.js',
							'scripts/core/**/*.js',
							'scripts/dev/**/*.js'
						]
					}
				}
			},


			// Config for grunt-contrib-jshint (javascript lint)

			jshint: {
				options: {
					reporter: require('jshint-stylish'),
					force: true,
					ignores: ['scripts/build.js', 'scripts/core/vendor/**/*.js'],
					'-W001': false,

					// Enforcing
					notypeof: true,
					funcscope: true,
					unused: false,
					globals: {
						browser: true,
						devel: true,
						jQuery: true,
						console: true,
						document: true,
						module: true
					},

					// Relaxing
					asi: true,
					eqnull: true,
					loopfunc: true,
					multistr: true
				},
				files: ['scripts/**/*.js']
			},


			// Config for grunt-browser-sync (browser synchronisation and auto-reloader)

			browserSync: {
				dist: {
					bsFiles: {
						src: [
							"images/*.*",
							"styles/*.css",
							"scripts/*.js",
							"*.html",
							"*.php",
						]
					},
					options: {
						minify: false,
						logLevel: "info",
						logConnections: true,
						logFileChanges: true,
						ghostMode: true,
						watchTask: true // < VERY important
					}
				}
			},


			// Config for grunt-contrib-watch (overseer)

			watch: {
				html: {
					options: { livereload: true },
					files: ['**/*.html']
				},
				php: {
					options: { livereload: true },
					files: ['**/*.php']
				},
				css: {
					options: { livereload: true },
					files: ['**/*.css']
				},
				sass: {
					options: { livereload: false },
					files: ['**/*.{scss,sass}'],
					tasks: ['sass', 'autoprefixer']
				},
				js: {
					options: { livereload: true },
					files: ['scripts/**/*.js', '!scripts/*.js'],
					tasks: ['uglify', 'jshint']
				}
			},


			// Config for grunt-contrib-imagemin (image compression)

			imagemin: {
				dist: {
					options: {
						optimizationLevel: 5
					},
					files: [{
						expand: true,
						cwd: 'img',
						src: ['**/*.{png,jpg,gif}'],
						dest: 'img/min'
					}]
				}
			}
		});


		// DEPENDENT PLUGINS =========================/

		grunt.loadNpmTasks('grunt-autoprefixer');
		grunt.loadNpmTasks('grunt-contrib-sass');
		grunt.loadNpmTasks('grunt-contrib-uglify');
		grunt.loadNpmTasks('grunt-contrib-jshint');
		grunt.loadNpmTasks('grunt-contrib-watch');
		grunt.loadNpmTasks('grunt-browser-sync');
		grunt.loadNpmTasks('grunt-contrib-imagemin');

		// TASKS =====================================/

		grunt.registerTask('default', ['browserSync', 'watch']);
	};

**Comment by jljorgenson18** [comment]
It seems to be working for me now after the latest patch. Not sure why this happened
