### ISSUE TITLE
No way to pass options in BrowserSync Command Line?

### ISSUE THREAD

**Issue by cachaito** [BrowserSync/grunt-browser-sync#101]
Hi!
I have npm package.json script section like:
```
"scripts": {
        "task-server": "browser-sync start --startPath .tmp/index.html --server --files .tmp"
    }
```
How I could pass a options config by this CLI way? Especially I wanted to open Browser-Sync in Chrome `browser: "Chrome"`

**Comment by shinnn** [comment]
http://www.browsersync.io/docs/grunt/

```js
browserSync: {
  bsFiles: {
    src : 'your_assets'
  },
  options: {
      // your options
  }
}
```

**Comment by cachaito** [comment]
Hi @shinnn I must admit, that I don't understand this answer. I don't use Grunt/ Gulp, just Npm script section in package.json to run Browser-Sync. How convert this json/ Grunt style configuration:

```
browserSync: {
  bsFiles: {
    src : 'your_assets'
  },
  options: {
      // your options
  }
}
```
to CLI way

```
"scripts": {
        "task-server": "browser-sync start --startPath .tmp/index.html --server --files .tmp"
    }
```
I'd like to add, that I don't want use flag --conf to create whole new bs-config.js but just overwrite/add one option: `browser: "Chrome"`

**Comment by shinnn** [comment]
Ah, OK I understood what you really want just now. It was better to open this issue in [browser-sync](https://github.com/BrowserSync/browser-sync) repo.

@shakyShane As @cachaito said CLI doesn't seem to support `--browser` flag. Any idea?

**Comment by cachaito** [comment]
I'm glad I could explain exactly what I meant. Lets wait for some answers :-)

**Comment by shakyShane** [comment]
That option is not implemented for the cli, yet.

https://github.com/BrowserSync/browser-sync/blob/master/lib/cli/opts.json

Please open a feature request ticket in https://github.com/BrowserSync/browser-sync/issues and we'll get around to it :)

**Comment by cachaito** [comment]
Opened at [link](https://github.com/BrowserSync/browser-sync/issues/552)
