### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by paulca55** [BrowserSync/grunt-browser-sync#103]
I'm trying to install the grunt-browser-sync plugin on Windows 8.1 using the following command:

npm install grunt-browser-sync --save-dev

However I just get errors (see screenshot). I had no trouble installing grunt-contrib-sass and grunt-contrib-watch though.

Any help would be appreciated.

![error](https://cloud.githubusercontent.com/assets/7057526/7306377/c3de2bec-e9fc-11e4-83b0-2e923d8de895.jpg)

**Comment by shinnn** [comment]
> node -v v0.10.32

Older node.

> npm -v 1.4.28

Ancient npm.

**Comment by paulca55** [comment]
Thank you shinnn I never thought of that, I'm quite new to this. However I've upgraded to the newest version and I still get an error.

![error2](https://cloud.githubusercontent.com/assets/7057526/7307762/d0c57b80-ea06-11e4-96cf-f8a7cb53b778.jpg)

**Comment by shinnn** [comment]
`engine.io-client` 1.5.1 uses an older version of `ws`. The new release of `engine.io-client` would fix this problem.

(Related: https://github.com/Automattic/engine.io-client/pull/378)

**Comment by paulca55** [comment]
Thank you so much that worked!
