### ISSUE TITLE
Allow the "open" config option to accept a local url

### ISSUE THREAD

**Issue by dtipson** [BrowserSync/grunt-browser-sync#104]
Currently, I need to use a particular vhost in order for a facebook app to work (and no, I can't add xip.io to the app domains).  This was easy enough to set up with a httpd.conf config pointing port 3000 at the vhost that I am passing to BS, meaning I could access the BS proxied url at localdev.domain.net:3000, which keeps my vhost domain in place and allows BS to do its magic.  But I can't easily open that url automatically when BS starts (it only opens localhost:3000, and then I have to switch it), which would be super useful to help clue in other developers where they can find the livereloading local url.  

That is, it would be ideal if I could use open like this (in a grunt config, in this case):

                    watchTask: true,
                    proxy: "localdev.domain.net",
                    port:3000,
                    open:"http://localdev.domain.net:3000",
                    ghostMode: {
                        scroll: true
                    }

**Comment by shakyShane** [comment]
The open option is reserved for Browsersync urls only.

You could easily perform this manually though using [opn](https://www.npmjs.com/package/opn)

```js
watchTask: true,
proxy: "localdev.domain.net",
port:3000,
ghostMode: {
                    scroll: true
},
callbacks: {
        ready: function (err, bs) {
            require("opn")("http://localdev.domain.net:3000");
        }
    }
```
