### ISSUE TITLE
Not auto refreshing

### ISSUE THREAD

**Issue by karneaud** [BrowserSync/grunt-browser-sync#105]
I'm using Yeoman/Grunt + BrowserSync to develop then run on PHP xampp. in the grunt file I have added following snippets...

```
   browserSync: {
		dev:
		{
			bsFiles: {
				src : ['test-folder/*.html','test-folder/views/*.html','test-folder/scripts/*.js','test-        folder/styles/*.css']
			},
			options: {
					proxy: "localhost.dev/test-folder",
					port:80,
					watchTask:true
			}
		} 
	  }
```

grunt task process flow compiles scripts from "app/" and copy to "..xampp/htdocs/test-folder/" then runs "browserSync" task

browsersync open browser and UI and watches folders

> Running "browserSync:dev" (browserSync) task
    [BS] [info] Proxying: http://localhost.dev
   [BS] Access URLs:
    ----------------------------------------------
       Local: http://localhost:81/test-folder
    External: http://192.168.0.2:81/test-folder
    ----------------------------------------------
          UI: http://localhost:3001
     UI External: http://192.168.0.2:3001
    ----------------------------------------------
  [BS] Watching files...

 then "grunt watch" task
grunt watch will track changes in "app" then copy to "xampp...../test-folder"

While all above executes successful browser-sync does not update/ reload browser. How do i get browserSync to watch "xampp.../test-folder'?

**Comment by garypburton** [comment]
If you are still having trouble with this issue [this](https://github.com/BrowserSync/grunt-browser-sync/issues/68) issue thread just really helped me as I was having a similar problem. It turned out the browser sync task couldn't find my `<body>` tag to inject the script into the file, my project is wordpress and it has the `body_class()` function in the body tag - hence no refresh or injection because although the task is watching the files etc it can't communicate with browser (or something like that). So I used the snippetOptions solution someone mentions near the bottom of that thread and that works fine.

Your grunt snippet looks fine to my, admittedly, untrained eyes.

**Comment by devert** [comment]
No matter what I do, I cannot get automatic css injection to work after updating to the latest version 2.1.3. JS and HTML changes reload fine. I've tried the new bsReload task and that did not make a difference. Triggered the bsReload task but did nothing. 

I'm compiling less with a watch task.

```
less: {
        options: {
            livereload: false,
            spawn: false
        },
        files: [
            '**/*.less'
        ],
        tasks: ['less:main']
    }
```

BrowserSync configuration is...

```
dev: {
        bsFiles: {
            src: [
                '/css/**/*.css',
                '/js/**/*.js',
                '**/*.cshtml'
            ]
        },
        options: {
            proxy: 'local.client.com',
            ghostMode: {
                clicks: false,
                forms: false,
                scroll: true
            },
            logLevel: 'info',
            logConnections: false,
            watchTask: true,
            open: 'ui',
            tunnel: 'client',
            xip: true
        }
    }
```

**Comment by karneaud** [comment]
MY problem was that I wasn't referencing the folder path which is outside of the development folder

**Comment by ryentzer** [comment]
I've tried the recommended steps mentioned above and others that I've come across but I cannot for the life of me get browserSync to work with my wordpress theme. My grunt file contains only browserSync.

```
module.exports = function(grunt) {
  grunt.initConfig({
    browserSync: {
      default_options: {
        bsFiles: {
          src: [
            "assets/styles/*.css",
            "**/*.php"
          ]
        },
        options: {
          logLevel: 'debug',
          logSnippet: true,
          notify: true,
          proxy: "localhost/treehouseDev"
        },
        // Customise the placement of the snippet
        snippetOptions: {
          rule: {
            match: /<!-- browsersync -->/i,
            fn: function (snippet, match) {
              return snippet + match;
            }
          }
        }
      }
    }
  });

  grunt.loadNpmTasks('grunt-browser-sync');

  grunt.registerTask('default', ['browserSync']);
};
```
I put the snippet match `/<!-- browsersync -->` in my footer.php file.

If I change the css file  [BS] sees and notes the change but the css change is NOT injected into the browser. In fact, the notification in the upper right does not appear when browserSync first opens the page. 

```
grunt --version
grunt-cli v0.1.13
grunt v0.4.5

npm --version
2.13.4
```
