### ISSUE TITLE
Not watching new files

### ISSUE THREAD

**Issue by rebelliard** [BrowserSync/grunt-browser-sync#106]
Once BrowserSync is running, it fails to detect any new files, although connect's `livereload` watch does effectively detect them and reload accordingly.

```
    browserSync: {
      proxy: {
        files: {
          src : [
            '.tmp/styles/**/*.css',
            'src/app/**/*.html',
            'src/app/**/*.js',
            'src/app/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}'
          ],
        },
      },
      options: {
        watchTask: true,
        proxy: '0.0.0.0:9000'
      }
    },
```

Here is my task runner:

```
grunt.task.run([
      'connect:server',
      'browserSync',
      'watch'
    ]);
```

**Comment by pionl** [comment]
Via grunt its not working too. The console writes only [BS] Watching files... with empty files.

**Comment by devner007** [comment]
I have a similar setup and its not working for me either. My code can be seen at: [browserSync does not reload PHP files on change](https://github.com/BrowserSync/grunt-browser-sync/issues/138)
