### ISSUE TITLE
Using BrowserSync with Wordpress

### ISSUE THREAD

**Issue by vongoh** [BrowserSync/grunt-browser-sync#113]
I have a grunt-sass setup to use Sass with Wordpress.   I have Wordpress installed on XAMPP so I'm already running a server.   

I want to refresh when I change CSS/PHP & JS in the Theme.

Can I use BrowserSync to  with this setup?  and what's the most straightforward way to do that - it would be awesome if somebody had a recipe for this, thanks!

**Comment by aolin480** [comment]
Did you ever get this answered? What does your theme folder look like? What is the domain that you are developing on (localhost/mykewlwpsite or www.mykewlwpsite.local, etc)? Give me a little insight on this and I can draw something up for you. As a fellow windows user, we have to stick together :p

**Comment by ganlub** [comment]
That's what are you looking for: https://www.browsersync.io/docs/options/#option-proxy

**Comment by shakyShane** [comment]
Sure, provide something like this in your Gruntfile

```js
browserSync: {
    dev: {
        options: {
            proxy: "your-wordpress.dev",
            files: ['wp-content/themes/your-theme']
        }
    }
}
```

**Comment by devner007** [comment]
Hi @shakyShane, I tried your code, but still the PHP files do not reload upon change. I have opened a new issue. Please look at: [](https://github.com/BrowserSync/grunt-browser-sync/issues/138)

Thank you!
