### ISSUE TITLE
Cannot connect browserSync with other device in my wifi !!

### ISSUE THREAD

**Issue by kytosai** [BrowserSync/grunt-browser-sync#131]
Hello, 

First, when i use browser-sync with ethernet to share ip with port ( 3000 ) for other device , everything ok ! But when i use wifi to share br, i cannot connect browsersycn on other my device ( laptop, mobile....).

How to fix this issue ? Please, i cannot good english, sorry !!

**Comment by BulatSa** [comment]
Reboot your PC or Mac
