### ISSUE TITLE
`debugInfo` option

### ISSUE THREAD

**Issue by ArmorDarks** [BrowserSync/grunt-browser-sync#136]
In project gruntfile there is an option `debugInfo`: https://github.com/BrowserSync/grunt-browser-sync/blob/master/Gruntfile.js#L113

I wonder, does it do anything, or it's some kind of obsolete option?

Because I can not find anything similar nor in `grunt-browser-sync` documentation, nor in `browser-sync` itself.

**Comment by mrhyde** [comment]
when set to **false** it should suppress any console log messages. see [v0.7.0](https://github.com/BrowserSync/browser-sync/wiki/Release-history#070---includes-breaking-changes)
but it was replaced with LogLevel option, see [v.1.1.0](https://github.com/BrowserSync/browser-sync/wiki/Release-history#110-major-release)
so it's safe to remove this options
