### ISSUE TITLE
browserSync does not reload PHP files on change

### ISSUE THREAD

**Issue by devner007** [BrowserSync/grunt-browser-sync#138]
I am using Grunt + browserSync + grunt-php. The server starts normally. The problem is that whenever I make changes to PHP files, the changes are not reloaded automatically in browser. I have to manually reload the page despite having the settings in place. Although browsersync does seem to identify the change, it does not reload the page. Here is the text from CLI:
```
[BS] File changed: src\index.php
>> File "src\index.php" changed.

```
Directory Structure:
```
my_app/
   src/
      index.php
      about.php
   dist/
```
Gruntfile.js:

```
"use strict";

module.exports = function (grunt) {

    grunt.initConfig({

        pkg: grunt.file.readJSON('package.json'),

        watch: {
            php: {
                files: ['src/**/*.php']
            }
        },

        browserSync: {
            dev: {
                bsFiles: {
                    src: 'src/**/*.php'
                },
                options: {
                    proxy: '127.0.0.1:8010', //our PHP server
                    port: 8080, // our new port
                    open: true,
                    watchTask: true
                }
            }
        },

        php: {
            dev: {
                options: {
                    port: 8010,
                    base: 'src'
                }
            }
        }

    });


    grunt.registerTask('default', [
        'php', // Using the PHP instance as a proxy
        'browserSync',
        'watch'             // Any other watch tasks you want to run
    ]);

};
```

**Comment by yanwsh** [comment]
Hello, do you have body tag inside your php file? Browsersync inject javascript code inside body tag, so if body tag is missing, it won't work. 

Please open your browser, right click your mouse and click "view page source".

please make sure following code is inside source code.

```javascript
<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.js?v=2.17.5'><\/script>".replace("HOST", location.hostname));
//]]>
</script>
```

**Comment by devner007** [comment]
**AWESOMEEEEEEEE!!!!!! YOU ROCK MAN!!!!! THANK YOU!  THANK YOU!  THANK YOU!**

You made my day!!! Can't thank you enough! I already had a body tag inside my PHP file. I just needed injecting the script tag into it. I just pasted it in my PHP file and now its reloading the PHP file whenever I make any change.

_Just curious:_ How did you even figure it out that something like this has to be done in order to fix it? Is it discussed in the docs somewhere that I may have missed?

Thanks a ton for your helpful answer!

**Comment by yanwsh** [comment]
Because i have the same issue with you. And I found i am missing a body tag which cause the script not be injected automatically.

**Comment by neilyongge** [comment]
@yanwsh 非常感谢，我几乎花了一个整个下午的时间在baidu search这个问题，为什么浏览器同步会那么奇怪，html can sync，but php can't sync. 是你的答案，让我解决了困难，再次感谢。

**Comment by pdnellius** [comment]
In case anyone else has this problem and the above do not fix, my issue is that I am emulating a live page using a <base> tag. Doing so causes the browsersync script to have the base url prepended, causing the script not to work.
