### ISSUE TITLE
BrowserSync opens new tab and changes port number on SCSS change

### ISSUE THREAD

**Issue by lukashillebrand** [BrowserSync/grunt-browser-sync#140]
When i make SCSS changes to a file, a new tab in the browser gets opened (Instead it should use the current active one) and the port number increases. How can I reload just the current active tab and inject the changes?

    module.exports = function (grunt) {
    require('load-grunt-tasks')(grunt); // npm install --save-dev load-grunt-tasks
    grunt.loadNpmTasks('grunt-browser-sync');

    grunt.initConfig({
        sass: {
            options: {
                outputStyle: 'compressed'
            },
            dist: {
                files: {
                    'wp-content/themes/test/style.css': 'wp-content/themes/test/scss/style.scss'
                }
            }
        },
        postcss: {
            options: {
                processors: [
                    require('autoprefixer')({
                        browsers: ['last 2 versions']
                    })
                ]
            },
            dist: {
                src: 'wp-content/themes/test/style.css'
            }
        },
        watch: {
            dev: {
                files: ['wp-content/themes/test/scss/**/*.scss'],
                tasks: ['default']
            }
        },
        browserSync: {
            dev: {
                bsFiles: {
                    src : [
                        '/wp-content/themes/test/*.css',
                        '/wp-content/themes/test/*.php'
                    ]
                },
                options: {
                    proxy: "localhost/test/de",
                    watchTask: true,
                    notify: false,
                    open: false,
                    reload: true,
                    spawn: true
                }
            }
        }
    });

    grunt.registerTask('default', ['sass','postcss','browserSync','watch']);
};

**Comment by Hardbitrocker** [comment]
+1
