### ISSUE TITLE
AJAX requests in proxy mode causing browser redirect

### ISSUE THREAD

**Issue by hellonicolas** [BrowserSync/grunt-browser-sync#29]
Hi there!

I'm running grunt-browser-sync in proxy mode, with the actual server running from MAMP Pro. I am running into an issue using JQuery's $.getJSON function for local JSON data – instead of the normal behind-the-scenes data grab, it does a hard redirect of the browser to that JSON file (on all synced browsers!). FYI, this only happens on AJAX requests piped through this server; external requests work fine.

For example, my proxy server is accessible here: http://10.1.10.56:3002/
...and I'm using $.getJSON to access this JSON file: http://10.1.10.56:3002/levels/test.json

Once I do that, all browsers just redirect to http://10.1.10.56:3002/levels/test.json

Any recommendations on how to get around that? Side note, it brings me great joy to watch all my browsers sync at once :)

Thanks!

**Comment by benthurley82** [comment]
4 years later and I just had a similar problem. A PUT request seemed to be working but I was also getting an error in the console that implied it was using GET. I struggled to find the problem but in the end noticed I only got the issue when using browsersync. Using the suggested fix of disabling ghostMode fixed the problem while allowing me to continue using browsersync.
