### ISSUE TITLE
Add support for http://xip.io/

### ISSUE THREAD

**Issue by xiwcx** [BrowserSync/grunt-browser-sync#41]
I ran in to a problem where typekit won't serve fonts because it needs some part of the address to be reliable. http://xip.io/ was the answer to that problem, but now if a server opens in the browser at `192.168.1.5:3002` i have to manually add `192.168.1.5.xip.io:3002`, which is not the end of the world, but I can see it adding confusion down the road with other developers on my team. It would be great if this functionality could be added or—if this is already possible—if the functionality could be documented.

Thanks.

**Comment by DanielTate** [comment]
Is this suppose to work with local addresses?
It seems typekit isn't loading for my local network even when using this...

I have added *.xip.io to my typekit settings and enabled xip: true in my gulp file.

My local address on the network is 192.168.1.75, when accessing this from my machine it's fine, from any other machine on the network it doesn't load typekit.

Any insights? Has this functionality changed?

**Comment by xiwcx** [comment]
Yes, @DanielTate, the exclusive purpose is to work with LAN addresses. Let me know if you've followed all of the steps in this article: http://welchcanavan.com/developing-locally-with-typekit-and-xip/

If you have, I'm not quite sure what could be going wrong, but I'll try to think of something.

**Comment by cvillanujr** [comment]
I ran into a similar problem, tried the settings for *.xip.io, localhost, mylocaldev.com but it didn't work. Long story short if you are using Adblock and Ghostery plugins in your browser make sure you disable/whitelist the domain you are using for your local development as in my case Ghostery was the culprit and was blocking Typekit.
