### ISSUE TITLE
browser-sync and autoprefixer

### ISSUE THREAD

**Issue by danyeah** [BrowserSync/grunt-browser-sync#50]
It's me once again :D
I'm heavily relying on this plugin so thats why im always here :)

I open this issue because i cannot make browser-sync and autoprefixer cooperate, for my understanding BS reloads the css once it has been compiled (using grunt-contrib-sass) while autoprefixer does the same, what you end up with in your browser is not the autoprefixed css but the BS css.

One workaround could be to work on temp files, meaning that bs watches one temp css file (autoprefixer would have to take the main css file and make a main.temp.css) so that when this temp file is modified it reloads the css.
Or we could just make an option to ignore first save.

Sorry suggestions and bug report is all i can offer :D i'm not sufficiently skilled in node

**Comment by shakyShane** [comment]
Also, we have fully working examples to play with now https://github.com/BrowserSync/recipes/tree/master/recipes/grunt.sass.autoprefixer
