### ISSUE TITLE
Getting error when running browserSync after other grunt tasks

### ISSUE THREAD

**Issue by Sawtaytoes** [BrowserSync/grunt-browser-sync#51]
After running all my compile tasks in grunt, I then run `browserSync` and then `watch`.

If I run `browserSync` then `watch`, no problems getting it to run.
If I run, for instance, `clean`,  `browserSync`, then `watch`, it will give me this error:

```
Running "browserSync:dev" (browserSync) task
Warning: Cannot read property 'prototype' of undefined Use --force to continue.
```

What's going on here?

**Comment by pravinweb** [comment]
I was facing similar issues, my code is as follows

**aliases.yaml**
> dev:
  description: 'Development tasks'
  tasks:
    - 'concurrent:devFirst'
    - 'concurrent:devSecond'

**concurrent.js**

> devFirst: [
		'jshint',
		'sass:dev',
		'assemble'
	],
	devSecond: [
		'browserSync',
		'watch'
	]

above configuration was showing me an error - This site can’t be reached

To fix this, I removed 'browsersync' and 'watch' from concurrent task,

**aliases.yaml**
> dev:
  description: 'Development tasks'
  tasks:
    - 'concurrent:devFirst'
    - browserSync
    - watch


hope this will help someone.


Thanks,
Pravin
