### ISSUE TITLE
Weird issue with CSS live-injection in Chrome

### ISSUE THREAD

**Issue by ghost** [BrowserSync/grunt-browser-sync#53]
Hey Shane,

I have this really weird bug where when I use the watch task with sass (ruby or libsass), the browser gets the live injected CSS, but I have to hover or focus inside Chrome for the actual change to happen. Here's a gif showing the behaviour:

![browser-sync-chrome-focus](https://cloud.githubusercontent.com/assets/136990/2805174/f37b996e-ccb3-11e3-8e9f-86858c278632.gif)

Tested with both the gulp and grunt plugins.

Here's my grunt config for reference:

``` javascript
dev: {
    bsFiles: {
      src: [
        'public/assets/css/*.css',
        'public/assets/img/*.jpg',
        'public/assets/img/*.png',
        'public/assets/js/**/*.js',
        'public/**/*.php'
      ]
    },
    options: {
      open: true,
      startPath: '',
      notify: false,
      watchTask: true,
      timestamps: true,
      debugInfo: true,
      proxy: 'celsius-sopexa.dev',
      ghostMode: false
    }
  }
```

Any idea what could be causing this? I'm using the latest grunt plugin with the latest browser-sync (0.8.2)

**Comment by misterfresh** [comment]
Not sure if this is the same issue or a different one, but both in Firefox and Chrome I see a popup "main css injected" but no visible change. If I manually resize the window with a drag & drop, the changes appear. I'm using browser-sync following this recipe :  https://github.com/sogko/gulp-recipes/blob/master/browser-sync-nodemon-expressjs/gulpfile.js
Should I just reload the page on css change?
