### ISSUE TITLE
Not Reloading in IE

### ISSUE THREAD

**Issue by CharltonC** [BrowserSync/grunt-browser-sync#65]
Hello,

Context:
- I use Wamp for local server. The sample project file as well as the the GruntFile.js are located under localhost/temp/  directory.
- grunt.registerTask("monitor", ["browserSync", "watch"]);    has also been set.
- Here is the setting I currently have in Grunt:

browserSync: {
  options: {
      server: { baseDir: "./" },
      browser: ["google chrome", "firefox", "internet explorer"],
      open: false,
      watchTask: true
  },
  task: { src: ["index.html"] }     // i tried task: { bsFiles: { src: ["index.html"] } } which gives same result
}

Problem:
When I enter localhost/temp in the Url, it is replaced with localhost:3000 in both Chrome and Firefox however not in IE. The reloading in both browsers work fine if watched file is changed however not in IE, only until I change the IE Url to localhost:3000 as well it will then work. (I originally thought it may have to do with the name of IE browser)

It looks like there may be something in the browserSync setting I should correct.  Any advice would be much appreciated.

**Comment by pixwell** [comment]
Hi, I know it's been a long time, but I hope this answer helps others.
In order to reload in IE (Internet Explorer), you have to include the correct name: **"iexplore"** (not iexplore**R**), like follow:

```
browserSync: {
    options: {
        server: { baseDir: "./" },
        browser: ["google chrome", "firefox", "iexplore"], //Yes!! without "R" in the end
        open: false,
        watchTask: true
},

task: { src: ["index.html"] } // i tried task: { bsFiles: { src: ["index.html"] } } which gives same result
}

```

[]'s

**Comment by amedina14** [comment]
Thank you!
