### ISSUE TITLE
Grunt task takes more than 1 second to complete

### ISSUE THREAD

**Issue by ghost** [BrowserSync/grunt-browser-sync#84]
I dont know if this is the default behaviour of browsersync but I feel a bit slow with my current setup. When I hit save, it takes at least 1s to refresh/inject. Just setup my grunt tasks, there is only the watch task with browsersync and grunt-contrib-sass.

```
Running "browserSync:dev" (browserSync) task

Running "watch" task
Waiting...
[BS] Proxying: http://172.17.0.4
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:3000
[BS] External URL: http://172.17.0.6:3000
[BS] Watching files...
[BS] File changed: app/styles/main.scss
>> File "app/styles/main.scss" changed.
[BS] Browser Connected: Chrome, version: 18.0.1025.166
[BS] Browser Connected: Chrome, version: 18.0.1025.166
Running "sass:dev" (sass) task

Done, without errors.


Execution Time (2014-12-10 03:53:20 UTC)
loading tasks    5ms  ▇▇▇▇ 3%
sass:dev       193ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 97%
Total 198ms

Completed in 1.478s at Wed Dec 10 2014 03:53:20 GMT+0000 (UTC) - Waiting...
[BS] File changed: app/styles/main.css
```

As you can see, the sass:dev task is actually quite fast, though I've only one line of css in there. Lets take a look at my Gruntfile: http://paste.ubuntu.com/9450991/ (not done yet). The weird thing is, I've to set browsersync to watch my scss AND css file, which is generated. If I remove the scss glob pattern, the page doesnt get reloaded then. Can you tell me how fast your browsersync task is and if it is really an issue with my setup? I may remember it was a lot faster the last time I used...

PS: Im using a docker container for my LAMP setup linked to a "frontend-dev" container to get my work done. That's why Im using an environment variable to proxy the connection. 

PPS: I dont think it is an issue with my tasks itself. I'll try a different version of browser-sync and see if I get a boost there. :horse:

**Comment by k0377** [comment]
What the hell is browsersync doing? I've still this issue it is so slow... u know like S L O W P O K E! :pig:
It has definetely to do with browsersync, i mean look at my execution time: loading tasks in 4ms, sass task needs 250ms so I've to wait 2 seconds for browsersync?!!? I tried debug mode but I dont get more info what browsersync is doing or not doing. Debug shows only more information on browsersync start-up.

```
Execution Time (2015-02-21 03:54:15 UTC)
loading tasks    4ms  ▇▇▇ 2%
sass:dev       231ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
Total 236ms

[BS] File changed: app/styles/main.css
Completed in 2.280s at Sat Feb 21 2015 03:54:15 GMT+0000 (UTC) - Waiting...
```

**Comment by k0377** [comment]
Okey, I got this now working. The problem were some tasks I didnt used anyway so Im now super fast with 0.5 - 0.8 seconds. :hamster:
