### ISSUE TITLE
Trouble customizing socket namespace

### ISSUE THREAD

**Issue by leigeber** [BrowserSync/grunt-browser-sync#87]
We are trying to figure out a way to support HTTPS development and are running into an issue. The hacky solution we've worked up is to always run the proxy since it supports HTTPS so we can grab the secure reload snippet. Then we paste that into our code. That part works fine and the source of the browser sync script looks correct.

Where we're getting hung up is the socket namespace to keep it pulling from localhost and not the local virtual host URL. We are settings the following:

```
grunt.config.set('browserSync.options.scriptPath', function(path) {
	return 'https://localhost:9000' + path;
});

grunt.config.set('browserSync.options.socket.namespace', function(namespace) {
	return 'https://localhost:9000' + namespace;
});
```

It appears to load everything correctly looking at the net panel but the response to one of the subsequent responses is below:

```
�44/browser-sync/socket.io,"Invalid namespace"
```

Hope that makes sense. Any ideas?

**Comment by cajoy** [comment]
have the same issue but without HTTPS...

Have no clue how to resolve it...

**Comment by shakyShane** [comment]
Please see: https://github.com/BrowserSync/browser-sync/issues/690.

You can now explicitly set *just* the domain for the socket connection.

To get this fix within the grunt plugin, you'll need to

```js
npm rm grunt-browser-sync && npm i grunt-browser-sync
```
