### ISSUE TITLE
trouble changing server

### ISSUE THREAD

**Issue by vlrprbttst** [BrowserSync/grunt-browser-sync#88]
Hi shane,
i'm sure this is not an issue with your plugin but i've been trying to change the localhost server from localhost:3000 to my xampp virtual server (localhost/my-website) but couldn't get around it. what am i missing? here's my gruntfile 

```js
browserSync : {
    dev : {
        bsFiles : {
            src : ['css/*.css', 'images/*.*', 'js/build/production.min.js', '*.html']
        },
        options : {
            server : {
                baseDir : "./", 
                proxy : "localhost/my-website"

            },
            watchTask : true
        }
    }
}
```

i've moved that proxy : "localhost/my-website" around but either i get an error (Fatal error: Object #<Object> has no method 'charAt') or it keeps the localhost:3000

help would be greatly appreciated :) thank you so much and greetings for the wonderful work!

**Comment by shakyShane** [comment]
You have mistakes in your configuration.

Try this: 

```js
    browserSync : {
        dev : {
            bsFiles : {
                src : ['css/*.css', 'images/*.*', 'js/build/production.min.js', '*.html']
            },
            options : {
                proxy : "localhost/my-website"
                watchTask : true 
            }
        }
    }
```

**Comment by vlrprbttst** [comment]
it works! but it doesn't auto-refresh the page. i tried "server" instead of proxy but i get "Cannot GET /"
i guess proxy is the way to go but doesn't it auto-refresh? thanks!

**Comment by vlrprbttst** [comment]
ok so what i have to do is manually changing the proxy address that opens automatically adding :3000.
it opens localhost/my-website but no livereload here so i have to change it to localhost:3000/my-website and then it works. correct?

**Comment by shakyShane** [comment]
Which version are you running?   `npm ls browser-sync`

**Comment by vlrprbttst** [comment]
browser-sync@1.3.6

**Comment by shakyShane** [comment]
Please check http://www.browsersync.io/docs/#requirements. 

Should this not solve your issue, please feel free to reply here with a sample HTML document that shows your issue.
