### ISSUE TITLE
Use browserSync with a server other than grunt.

### ISSUE THREAD

**Issue by devedmo** [BrowserSync/grunt-browser-sync#89]
Hello Dear,

I have to working in my application with Apache Tomcat. I use Grunt for tasks in my build. I am setting my project with port 8080, but this port is in use for Apache.

I saw a problem with that in another time: [specifying port 80 gives me port 81 #290](https://github.com/shakyShane/browser-sync/issues/290).

My question if is possible use Apache Tomcat + browserSync? Since the port is being used by a server other than grunt?

**Comment by krisak** [comment]
Your webserver runs on certain port and you can run browsersync on any port. You can then run browser sync in proxy mode and point proxy to your webserver port. It is in the [documentation](http://www.browsersync.io/docs/grunt/) look under proxy.

**Comment by shakyShane** [comment]
yep, what @krisak said!

**Comment by devedmo** [comment]
thanks @krisak and @shakyShane !
