### ISSUE TITLE
proxy url still wants to go to http://localhost:3000

### ISSUE THREAD

**Issue by danny-englander** [BrowserSync/grunt-browser-sync#93]
I have input my proxy url to match my local vhost (d8.dev): 

```js
browserSync: {
      dev: {
        bsFiles: {
          src : '<%= paths.devCSS %>/'
        },
        options: {
          proxy : "d8.dev",
          watchTask: true
        }
      }
    },
```
But when I make changes to my sass, I get another tab that opens at http://localhost:3000/. Here is what I see print out in terminal:

```bash
Running "browserSync:dev" (browserSync) task
[BS] Proxying: http://d8.dev
[BS] Access URLs:
 -------------------------------------
 Local: http://localhost:3000
 External: http://192.168.1.83:3000
 -------------------------------------
 UI: http://localhost:3001
 UI External: http://192.168.1.83:3001
 -------------------------------------
[BS] Watching files...
```

It's weird because the first part of the the printout seems right, i.e ```Proxying: http://d8.dev```. So I am not sure what I am doing wrong.

**Comment by shakyShane** [comment]
You are supposed to access your site via the `Access URLS` provided, **not** your original one.
