### ISSUE TITLE
[Question] npm install browser-sync -g

### ISSUE THREAD

**Issue by marocas** [BrowserSync/grunt-browser-sync#94]
If i install BS globally, how can i call BS and get my bs-config.js file to make my server.

ATM im running with grunt-bs, its working fine, but since theres a global installation, and i dont need to install BS every time i start a new project.
How can i make it to run?

Atm, my folder is like this:
```
--project
|--config
|  |--bs-config.js
|  |--browserSync.json
|  |--all my tasks
|-node_modules
| |-grunt-browser-sync  <-- want to remove this if i have BS global installation.
| |-all my grunt dep
|-gruntfile.js
|-package-json
|-etc...
```
On my bs-config, it have the browser-syn init configuration, but i cant call it from the global installation.
To run the server now, i call browserSync.json file that have:
```js
// folder: config/browserSync.json
{
  "bsFiles": {
    "src": [
      "<%= cfg.root %><%= cfg.dest.styles %>**/*.css",
      "<%= cfg.root %><%= cfg.dest.html %>**/*.html",
      "<%= cfg.root %><%= cfg.src.scripts %>**/*.js",
      "<%= cfg.root %><%= cfg.src.html %>**/*.hbs",
      "<%= cfg.root %>index.html",
      "Gruntfile.js"
    ]
  },
  "options": {
    "watchTask": true,
    "open": "ui",
    "timestamps": false,
    "server": {
      "baseDir": [
        "<%= cfg.root %>",
        "<%= cfg.root %><%= cfg.dest.html %>"
      ]
    }
  }
}
```
But i have to have grunt-browser-sync installed on my project.
Best regards.

**Comment by shakyShane** [comment]
If using grunt, you must install BrowserSync locally to each project.

Your configuration is grunt-specific and therefore will not work without it.

If you just want to load the config file that's created with `browser-sync` init, just run 

```bash
browser-sync start --config <path to your file>
```
