### ISSUE TITLE
installation fails on windows with node 0.12.0

### ISSUE THREAD

**Issue by eikaramba** [BrowserSync/grunt-browser-sync#95]
as title suggest installation fails with messages like
```
X:\xxx\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_module s\nan\nan.h(213): error C2039: 'ThrowException' : is not a member of 'v8' [X:\xxx\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules \socket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
X:\xxx\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_module s\nan\nan.h(213): error C2039: 'New' : is not a member of 'v8::String' [X:\xxx\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\so cket.io-client\node_modules\engine.io-client\node_modules\ws\build\bufferutil.vcxproj]
```
I guess it is because of the NAN module inside socket project resp. websocket(ws) - but.... yeah i dunno where to leave it so i thought about opening an issue here, just in case any other people ran into the same problem.

**Comment by eikaramba** [comment]
also it fails after this line
X:\xxx\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>node "X:\programs\node.js\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc

just in case this helps

**Comment by eikaramba** [comment]
ahhh i changed the dependency in the ws package for nan to 1.6.x and executed "node-gyp rebuild" in the folder again. It compiled successfully and browser-sync is now working.

**Comment by jhuskisson** [comment]
Great to hear!
