### ISSUE TITLE
Upgrading module and using manual snippet

### ISSUE THREAD

**Issue by jegtnes** [BrowserSync/grunt-browser-sync#99]
Hey Browsersync! Thanks for the awesome tool, 2.x is really fantastic and helps me make stuff quicker every day. 😻

Quick query regarding using the manual snippet—every time a new 2.x.x release goes out, whichever team member upgrades their modules first breaks BrowserSync, as the snippet URL needs to be updated from e.g. `browser-sync-client.2.2.1.js` to `browser-sync-client.2.2.2.js`, which means that everybody working on the same project need to update their npm modules. I know I can lock the npm version number down to a specific release, but we don't want to miss out on cool upgrades either! Is there a way to just link to a major version of the snippet, say, `browser-sync-client.2.js`?

P.S. Sorry if this belongs in the main browser-sync repo, I wasn't sure where to post it.

Cheers!

**Comment by hugobessaa** [comment]
The last time I checked, it works if you simply use `browser-sync-client.js` :).

**Comment by shakyShane** [comment]
Yep, @hugobessaa is correct

https://github.com/BrowserSync/browser-sync/blob/master/lib/server/snippet-server.js#L17
